### PR TITLE
Support multi instance

### PR DESCRIPTION
**Pull request by ngot**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by ngot** [comment]
这就合了？ 我准备迁移到官方仓库去维护。

**Comment by zcong1993** [comment]
好的

**Comment by ngot** [comment]
@zcong1993 npm的owner也加我一下一下把，我的id: ngot 我来迁移到官方group维护起来

**Comment by zcong1993** [comment]
@ngot 加了

**Pull request merged**
